---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - tillix
        - vim
        - zsh
  
  - name: Install Oh My Zsh
    become: false
    shell: |
      sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
    args:
      executable: /bin/bash

  - name: .zshrc file
    copy:
      src: files/zshrc
      dest: ~/.zshrc
      owner: <hostname>
      group: <hostname>
