---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - tillix
        - vim
        - zsh

  - name: .zshrc file
    copy:
      src: files/zshrc
      dest: ~/.zshrc
      owner: <hostname>
      group: <hostname>
