
export ZSH="$HOME/.oh-my-zsh"
#ZSH_THEME="avit"
#ZSH_THEME="alanpeabody"
#ZSH_THEME="fino-time"
ZSH_THEME="bira"
DEFAULT_USER=$USER
plugins=(git zsh-autosuggestions zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh
source /etc/zsh_command_not_found

